### ISSUE TITLE
missing dependency : libssl-dev

### ISSUE THREAD

**Issue by jolan78** [simsong/tcpflow#103]
on ubuntu (and other debian-based distributions ?) you need to install libssl-dev.

**Comment by simsong** [comment]
The dependency is documented in the configure.ac file:

```checking for SSL_library_init in -lssl... no
configure: error: OpenSSL developer library 'libssl-dev' or 'openssl-devel' not installed
[ec2-user@ec2 tcpflow]$ ls /usr/lib/*ssl*
```

However, it now seems that libssl-dev now requires that you have -ldl and the module wasn't previously using that. How would *you* like the dependency to be documented?

**Comment by jolan78** [comment]
Ok, I was using http://www.digitalcorpora.org/downloads/tcpflow/tcpflow-1.4.4.tar.gz which does not display that warning. I should use the dev. tree.
The configure.ac hint is a great way to help the user, but updating README.md's apt-get command would't hurt.
I did't have any issue with -ldl, it's in libc6-dev, which is a dependency of gcc...

thank you.

**Comment by simsong** [comment]
Please update the docs and send a pull request.
