### ISSUE TITLE
-J no longer supported, but still listed in the manpage

### ISSUE THREAD

**Issue by dkogan** [simsong/tcpflow#107]
Hi. tcpflow 1.4.5:

```
$ tcpflow -J |& head -n 2
tcpflow: invalid option -- 'J'
tcpflow[12645]: error: unrecognized switch '?'
```

So -J is now broken, or has been removed. If it was removed, the manpage should be updated.

**Comment by simsong** [comment]
No, it's renamed '-g'
But I'm not sure why.
Can you see if -g works?

**Comment by dkogan** [comment]
Simson L. Garfinkel <notifications@github.com> writes:

> No, it's renamed '-g'
> But I'm not sure why.
> Can you see if -g works?

It seems to work. If that's the intent, can you please update the docs?
Thanks.

**Comment by simsong** [comment]
done.
