### ISSUE TITLE
cannot determine transmission order from the generated file names

### ISSUE THREAD

**Issue by emmanueltouzery** [simsong/tcpflow#110]
I am trying to use `tcpflow` to filter out a specific transmission from a dump. It works in the sense that all the pieces of the transmission get extracted as individual files and they are nicely split from data not belonging to that transmission.

My problem is that I did not find a way to get from the generated file names the order of appearance of the data in the dump. So I have the files from the transmission but I don't know how to reorder them from the filename for instance. The port changes several times during the transmission, there are several files with the same connection count, also the `t` and `T` timestamp repeat, so I'm not sure how to get around to sort them.

I run `tcpflow` like that:

    tcpflow -a -o outdir -FT -r packets.pcap

Would it be possible to add a new option under `-F` with the packet number of the first packet in the file, so that I can sort the files by their time of appearance in the original dump?

**Comment by emmanueltouzery** [comment]
i just understood why the `t` and `T` timestamp are the same for all the files. I think those apply really when you capture the stream already with `tcpflow`. But in my case it's from a capture that's now on disk. So in that case that time is useless as `tcpflow` works through the data too fast for the timestamp to change. I'll try to capture directly with tcpflow but the feature would still be useful anyway.

**Comment by simsong** [comment]
The files have their timestamps set by when they appear in the dump file. You could sort by that. Alternatively, you can look in the XML file; all of the information you want is there.

**Comment by simsong** [comment]
The timestamps are taken from the packet timestamps.

**Comment by emmanueltouzery** [comment]
ok i looked a bit more at the XML file now. So it seems the files that have the same timestamp are byte runs from a single "file". Individual byte runs have the same timestamp. but i can indeed get the info from the XML it seems. Or even make a recording directly with `tcpflow` as I mentioned and use the OS timestamps. So it seems all the needs I have are already covered. Thank you for your answer, I'll close the issue now then...
