### ISSUE TITLE
Where is v1.4.6?

### ISSUE THREAD

**Issue by roshanjames** [simsong/tcpflow#117]
I don't see version 1.4.6 in the downloads, though that's the latest version as per the main page.

**Comment by simsong** [comment]
Sorry.

You can make your own download by cloning the git repository and doing a 'make dist'

That will need to do until later...



----

**Comment by roshanjames** [comment]
Thanks. Will do.

**Comment by simsong** [comment]
Closed, as current version is 1.5.1, and that's not available for download either...
