### ISSUE TITLE
Combining output files into pairs

### ISSUE THREAD

**Issue by vfaronov** [simsong/tcpflow#128]
I would like to combine the files produced by tcpflow into pairs: the outgoing stream and the incoming stream for each connection.

As far as I understand, this is not currently possible with tcpflow, because there is no information in the filename that can be used as a “unique key” of a connection. I cannot use just the source+destination address+port, because these can happen later on a different connection. I cannot also require that the timestamp be the same, because a connection’s incoming packets may start arriving at a later timestamp than its outgoing packets. And as for tcpflow’s “connection counter”, that seems to be merely a way of avoiding filename collisions, not any form of stable identifier.

Is my understanding correct?

If so, it would be nice to have some sort of “connection ID” that would be guaranteed (or exceedingly likely) to be unique for the lifetime of a tcpflow process.

**Comment by leveryd** [comment]
yeah,i think it is a good feature.

**Comment by simsong** [comment]
Added in https://github.com/simsong/tcpflow/pull/212.
