### ISSUE TITLE
-FT only output UTC timestamp

### ISSUE THREAD

**Issue by TanyaTie** [simsong/tcpflow#131]
My local timezone is JST, however when I use "-FT" option, the file name output as UTC timezone.

**Comment by TanyaTie** [comment]
example:
$date
Tue Oct  4 19:43:16 JST 2016
$sudo tcpflow -i eth0 -o ./ -FT
2016-10-04T10:43:32ZXXX.XXX.093.045.00080-192.168.100.003.36811

**Comment by simsong** [comment]
This is the correct behavior. Time is in UTC, not in local timezone.
