### ISSUE TITLE
piping tcpflow output

### ISSUE THREAD

**Issue by behramkhan** [simsong/tcpflow#133]
Hi I want to pipe output of tcpflow to netcat

tcpflow -c -i eth1 port 514 | stdbuf -i0 -o0 -e0 awk '{$1="";sub(" ",""); | nc 

I am actually sending a file containing a single line (4MB in size) from source to destination and I am using tcpflow to recreate the file. 

What I want is to pipe the output of tcpflow to another machine. Tcpflow is splitting the data and then piping it in chunks rather than one singe line.

How can I configure tcpflow to buffer a complete message before (piping) forwarding it. 

thanks

**Comment by simsong** [comment]
Hi. tcpflow doesn't have this capability. If you want to buffer like this, I would recommend creating a pipe program that does it. This would not be a feature that has general usefulness, although it might be useful in your particular application. 

Why are you trying to do this? If it is to prevent the tcp connection from being dropped, then you should buffer to a file. If you don't think that there is enough file system space, then you could make a RAM disk. If you don't have enough memory or file system space, then you wouldn't be able to buffer it in tcpflow, either.

**Comment by behramkhan** [comment]
Hi, Thanks for your comment.

Actually I have messages the are one liners (no line delimiters) but quite big. What I wanted to do is to capture a message from tcpflow and pipe it to the next machine. It is important that I pass the info as soon as I get it so rather than buffering it in a file so I thought I could just pipe it as tcpflow might be doing line buffering.

It is imp that the message is forwarded by netcat in its entirety so I cannot afford splitting of messages and hence my question.

Thanks

**Comment by simsong** [comment]
tcpflow is not performing any buffering. If you think that a large message is being sent via netcat to a remote system without buffering, you are mistaken. There are lots of buffers in lots of places.

**Comment by behramkhan** [comment]
Thanks simsong.
