### ISSUE TITLE
tcpflow RPM

### ISSUE THREAD

**Issue by behramkhan** [simsong/tcpflow#137]
Just wanted to know if there is any way of "making" an RPM for tcpflow.

**Comment by simsong** [comment]
Yes, it's possible.

**Comment by behramkhan** [comment]
Hi, Thanks for the reply. If you could please give some details of the command to run to produce the binary rmp. thanks

**Comment by simsong** [comment]
Sorry, there are many online references on how to make RPMs. I can't help you.


----
