### ISSUE TITLE
Http file format confusing

### ISSUE THREAD

**Issue by bts-webber** [simsong/tcpflow#143]
HI,
   I use command "tcpflow -a -i eth0 -e http ",but I found if there is Get data behind the Post data, Get data format will be confusing.

![formaterror](https://cloud.githubusercontent.com/assets/8574016/22724059/a1845870-edfe-11e6-84cf-ba4cbb80ded1.png)

**Comment by simsong** [comment]
Yes, HTTP/1.1 can be confusing. However, it is not the job of tcpflow to make it less confusing.
