### ISSUE TITLE
Compile error on Debian Sid

### ISSUE THREAD

**Issue by Code7R** [simsong/tcpflow#147]
amd64, g++ 6.3, result:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for prefix by checking for tcpflow... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
configure: Compiling under .
configure: checking /usr/local/include
configure:  *** ADDING /usr/local/include to CPPFLAGS *** 
configure:  *** ADDING /usr/local/lib to LDFLAGS *** 
configure: checking /opt/local/include
configure: checking /sw/include
configure: checking /usr/local/ssl/include
configure:  CPPFLAGS = -I/usr/local/include  
configure:  LDFLAGS = -L/usr/local/lib  
C Warnings to test: -MD -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes     -Wshadow -Wwrite-strings -Wcast-align -Waggregate-return     -Wbad-function-cast -Wcast-qual -Wundef -Wredundant-decls -Wdisabled-optimization     -Wfloat-equal -Wmultichar -Wc++-compat -Wmissing-noreturn  -Wall -Wstrict-prototypes
checking whether gcc understands -MD... yes
checking whether gcc understands -Wpointer-arith... yes
checking whether gcc understands -Wmissing-declarations... yes
checking whether gcc understands -Wmissing-prototypes... yes
checking whether gcc understands -Wshadow... yes
checking whether gcc understands -Wwrite-strings... yes
checking whether gcc understands -Wcast-align... yes
checking whether gcc understands -Waggregate-return... yes
checking whether gcc understands -Wbad-function-cast... yes
checking whether gcc understands -Wcast-qual... yes
checking whether gcc understands -Wundef... yes
checking whether gcc understands -Wredundant-decls... yes
checking whether gcc understands -Wdisabled-optimization... yes
checking whether gcc understands -Wfloat-equal... yes
checking whether gcc understands -Wmultichar... yes
checking whether gcc understands -Wc++-compat... yes
checking whether gcc understands -Wmissing-noreturn... yes
checking whether gcc understands -Wall... yes
checking whether gcc understands -Wstrict-prototypes... yes
checking how to run the C++ preprocessor... g++ -E
checking string usability... yes
checking string presence... yes
checking for string... yes
C++ Warnings to test: -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith     -Wshadow -Wwrite-strings -Wcast-align      -Wredundant-decls -Wdisabled-optimization     -Wfloat-equal -Wmultichar -Wmissing-noreturn     -Woverloaded-virtual -Wsign-promo     -funit-at-a-time  -Weffc++
checking whether g++ understands -Wall... yes
checking whether g++ understands -MD... yes
checking whether g++ understands -D_FORTIFY_SOURCE=2... yes
checking whether g++ understands -Wpointer-arith... yes
checking whether g++ understands -Wshadow... yes
checking whether g++ understands -Wwrite-strings... yes
checking whether g++ understands -Wcast-align... yes
checking whether g++ understands -Wredundant-decls... yes
checking whether g++ understands -Wdisabled-optimization... yes
checking whether g++ understands -Wfloat-equal... yes
checking whether g++ understands -Wmultichar... yes
checking whether g++ understands -Wmissing-noreturn... yes
checking whether g++ understands -Woverloaded-virtual... yes
checking whether g++ understands -Wsign-promo... yes
checking whether g++ understands -funit-at-a-time... yes
checking whether g++ understands -Weffc++... yes
checking whether g++ supports C++11 features by default... yes
configure: checking /usr/local/include
configure:  *** ADDING /usr/local/include to CPPFLAGS *** 
configure:  *** ADDING /usr/local/lib to LDFLAGS *** 
configure: checking /opt/local/include
configure: checking /sw/include
configure: checking /usr/local/ssl/include
configure: checking /usr/boost/include/include
configure:  CPPFLAGS = -I/usr/local/include -I/usr/local/include  
configure:  LDFLAGS = -L/usr/local/lib -L/usr/local/lib  
Warnings to test: -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes     -Wshadow -Wwrite-strings -Wcast-align -Waggregate-return     -Wbad-function-cast -Wcast-qual -Wundef -Wredundant-decls -Wdisabled-optimization     -Wfloat-equal -Wmultichar -Wc++-compat -Wmissing-noreturn  -Wall -Wstrict-prototypes
checking whether gcc understands -MD... yes
checking whether gcc understands -D_FORTIFY_SOURCE=2... yes
checking whether gcc understands -Wpointer-arith... yes
checking whether gcc understands -Wmissing-declarations... yes
checking whether gcc understands -Wmissing-prototypes... yes
checking whether gcc understands -Wshadow... yes
checking whether gcc understands -Wwrite-strings... yes
checking whether gcc understands -Wcast-align... yes
checking whether gcc understands -Waggregate-return... yes
checking whether gcc understands -Wbad-function-cast... yes
checking whether gcc understands -Wcast-qual... yes
checking whether gcc understands -Wundef... yes
checking whether gcc understands -Wredundant-decls... yes
checking whether gcc understands -Wdisabled-optimization... yes
checking whether gcc understands -Wfloat-equal... yes
checking whether gcc understands -Wmultichar... yes
checking whether gcc understands -Wc++-compat... yes
checking whether gcc understands -Wmissing-noreturn... yes
checking whether gcc understands -Wall... yes
checking whether gcc understands -Wstrict-prototypes... yes
not using clang
checking whether g++ understands -Wall... yes
checking whether g++ understands -MD... yes
checking whether g++ understands -D_FORTIFY_SOURCE=2... yes
checking whether g++ understands -Wpointer-arith... yes
checking whether g++ understands -Wshadow... yes
checking whether g++ understands -Wwrite-strings... yes
checking whether g++ understands -Wcast-align... yes
checking whether g++ understands -Wredundant-decls... yes
checking whether g++ understands -Wdisabled-optimization... yes
checking whether g++ understands -Wfloat-equal... yes
checking whether g++ understands -Wmultichar... yes
checking whether g++ understands -Wmissing-noreturn... yes
checking whether g++ understands -Woverloaded-virtual... yes
checking whether g++ understands -Wsign-promo... yes
checking whether g++ understands -funit-at-a-time... yes
checking whether g++ understands -Wstrict-null-sentinel... yes
checking whether g++ understands -Weffc++... yes
checking for uncompress in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking lightgrep/api.h usability... no
checking lightgrep/api.h presence... no
checking for lightgrep/api.h... no
checking for lg_create_pattern in -llightgrep... no
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking tre/tre.h usability... no
checking tre/tre.h presence... no
checking for tre/tre.h... no
checking for regcomp in -lregex... no
checking for tre_regcomp in -ltre... no
checking for regcomp... yes
checking for tre_regcomp... no
checking for tre_version... no
checking openssl/aes.h usability... yes
checking openssl/aes.h presence... yes
checking for openssl/aes.h... yes
checking openssl/bio.h usability... yes
checking openssl/bio.h presence... yes
checking for openssl/bio.h... yes
checking openssl/evp.h usability... yes
checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking openssl/hmac.h usability... yes
checking openssl/hmac.h presence... yes
checking for openssl/hmac.h... yes
checking openssl/md5.h usability... yes
checking openssl/md5.h presence... yes
checking for openssl/md5.h... yes
checking openssl/pem.h usability... yes
checking openssl/pem.h presence... yes
checking for openssl/pem.h... yes
checking openssl/rand.h usability... yes
checking openssl/rand.h presence... yes
checking for openssl/rand.h... yes
checking openssl/rsa.h usability... yes
checking openssl/rsa.h presence... yes
checking for openssl/rsa.h... yes
checking openssl/sha.h usability... yes
checking openssl/sha.h presence... yes
checking for openssl/sha.h... yes
checking for openssl/pem.h... (cached) yes
checking openssl/x509.h usability... yes
checking openssl/x509.h presence... yes
checking for openssl/x509.h... yes
checking for dlopen in -ldl... yes
checking for EVP_get_digestbyname in -lcrypto... yes
checking for MD5 in -lmd... no
checking for SSL_library_init in -lssl... no
checking for OPENSSL_init_ssl in -lssl... yes
checking for MD5_Init... yes
checking for EVP_get_digestbyname... yes
configure: Including dfxml_configure.m4 from dfxml
configure: Note: checks for afflib/afflib.h and libewf.h should be in the caller, so they can be disabled
checking err.h usability... yes
checking err.h presence... yes
checking for err.h... yes
checking expat.h usability... yes
checking expat.h presence... yes
checking for expat.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking sys/cdefs.h usability... yes
checking sys/cdefs.h presence... yes
checking for sys/cdefs.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking for unistd.h... (cached) yes
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking for fork... yes
checking for localtime_r... yes
checking for getuid... yes
checking for gethostname... yes
checking for getwpuid... no
checking for getrusage... yes
checking for mkstemp... yes
checking for vasprintf... yes
checking for regcomp... (cached) yes
checking exiv2/image.hpp usability... no
checking exiv2/image.hpp presence... no
checking for exiv2/image.hpp... no
checking for git... yes
configure: git commit tcpflow-1.4.0beta1-196-ga488679-dirty
checking for openssl/aes.h... (cached) yes
checking for openssl/bio.h... (cached) yes
checking for openssl/evp.h... (cached) yes
checking for openssl/hmac.h... (cached) yes
checking for openssl/md5.h... (cached) yes
checking for openssl/pem.h... (cached) yes
checking for openssl/rand.h... (cached) yes
checking for openssl/rsa.h... (cached) yes
checking for openssl/sha.h... (cached) yes
checking for openssl/pem.h... (cached) yes
checking for openssl/x509.h... (cached) yes
checking for EVP_get_digestbyname in -lcrypto... (cached) yes
checking for SSL_library_init in -lssl... (cached) no
checking for EVP_get_digestbyname... (cached) yes
configure: Including be13_configure.m4 from be13_api
checking for err.h... (cached) yes
checking for pwd.h... (cached) yes
checking for sys/cdefs.h... (cached) yes
checking for sys/mman.h... (cached) yes
checking for sys/resource.h... (cached) yes
checking for sys/utsname.h... (cached) yes
checking for unistd.h... (cached) yes
checking sqlite3.h usability... no
checking sqlite3.h presence... no
checking for sqlite3.h... no
checking for gmtime_r... yes
checking for ishexnumber... no
checking for isxdigit... yes
checking for localtime_r... (cached) yes
checking for unistd.h... no
checking for mmap... yes
checking for err... yes
checking for errx... yes
checking for warn... yes
checking for warnx... yes
checking for pread64... yes
checking for pread... yes
checking for strptime... yes
checking for _lseeki64... no
checking for utimes... yes
checking for sqlite3_libversion in -lsqlite3... no
checking for sqlite3_create_function_v2... no
configure: checking for unordered_map
configure:   CXXFLAGS:           -g -O2 -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Weffc++ -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Wstrict-null-sentinel -Weffc++
checking unordered_map usability... yes
checking unordered_map presence... yes
checking for unordered_map... yes
checking unordered_set usability... yes
checking unordered_set presence... yes
checking for unordered_set... yes
configure: done
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
Using settings from AX_PTHREAD
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for pthread_create in -lpthreadGC2... no
checking boost/version.hpp usability... yes
checking boost/version.hpp presence... yes
checking for boost/version.hpp... yes
checking boost/icl/interval.hpp usability... yes
checking boost/icl/interval.hpp presence... yes
checking for boost/icl/interval.hpp... yes
checking boost/icl/interval_map.hpp usability... yes
checking boost/icl/interval_map.hpp presence... yes
checking for boost/icl/interval_map.hpp... yes
checking boost/icl/interval_set.hpp usability... yes
checking boost/icl/interval_set.hpp presence... yes
checking for boost/icl/interval_set.hpp... yes
checking for XML_ParserCreate in -lexpat... yes
checking for pixman_region_init in -lpixman-1... yes
checking for BZ2_bzDecompress in -lbz2... yes
checking for FT_Init_FreeType in -lfreetype... yes
checking for FcBlanksCreate in -lfontconfig... yes
checking cairo/cairo.h usability... no
checking cairo/cairo.h presence... no
checking for cairo/cairo.h... no
checking cairo/cairo-pdf.h usability... no
checking cairo/cairo-pdf.h presence... no
checking for cairo/cairo-pdf.h... no
checking cairo.h usability... no
checking cairo.h presence... no
checking for cairo.h... no
checking cairo-pdf.h usability... no
checking cairo-pdf.h presence... no
checking for cairo-pdf.h... no
checking for cairo_create in -lcairo... no
configure: WARNING:
  *** cairo libraries not detected.
  *** Please install cairo-devel to get 1-page PDF summary generation.
  
checking pcap.h usability... no
checking pcap.h presence... no
checking for pcap.h... no
checking pcap/pcap.h usability... no
checking pcap/pcap.h presence... no
checking for pcap/pcap.h... no
checking for pcap_lookupdev in -lpcap... no
configure: WARNING:
Can't find the pcap library (libpcap.a).
tcpflow will not live capture or compile rules without pcap!

If you need rules or live capture, you must install the pcap and/or
pcap-dev library.  Please execute this command:

  UBUNTU: sudo apt-get install libpcap-dev
  DEBIAN: sudo apt-get install libpcap-dev
  FEDORA: sudo yum install libpcap-devel
  MINGW:  Sorry!  libpcap is not currently
          available when cross-compiling.

If your libpcap is installed in a non-standard location, you will need
to use the --with-pcap=directory to specify where your pcap is
located.
checking for ANSI C header files... (cached) yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking linux/if_ether.h usability... yes
checking linux/if_ether.h presence... yes
checking for linux/if_ether.h... yes
checking net/ethernet.h usability... yes
checking net/ethernet.h presence... yes
checking for net/ethernet.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking netinet/in_systm.h usability... yes
checking netinet/in_systm.h presence... yes
checking for netinet/in_systm.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking for regex.h... (cached) yes
checking semaphore.h usability... yes
checking semaphore.h presence... yes
checking for semaphore.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for sys/cdefs.h... (cached) yes
checking for sys/mman.h... (cached) yes
checking for sys/resource.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/types.h... (cached) yes
checking sys/bitypes.h usability... yes
checking sys/bitypes.h presence... yes
checking for sys/bitypes.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking for unistd.h... (cached) yes
checking for getdtablesize... yes
checking for net/if_var.h... no
checking for net/if.h... yes
checking for netinet/ip_var.h... no
checking for netinet/ip.h... yes
checking for netinet/ip_ether.h... no
checking for netinet/tcpip.h... no
checking for inet_ntop... yes
checking for sigaction... yes
checking for sigset... yes
checking for strnstr... no
checking for setuid... yes
checking for setgid... yes
checking for mmap... (cached) yes
checking for futimes... yes
checking for futimens... yes
checking for socklen_t... yes
checking for sa_family_t... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating doc/Makefile
config.status: creating doc/tcpflow.1
config.status: creating tcpflow.spec
config.status: creating config.h
config.status: executing depfiles commands
configure: *** You have missing libraries. To install them:
configure: *** Red Hat: sudo yum install cairo-devel   libpcap-dev 
configure: *** Fedora:  sudo dnf install cairo-devel   libpcap-dev 
configure: *** Ubuntu:  sudo apt-get install libcairo2-dev   libpcap-dev 
configure: *** MacOS:   sudo port install cairo-devel  libpcap 
make  all-recursive
make[1]: Verzeichnis „/home/ed/git/tcpflow/build-amake“ wird betreten
Making all in src
make[2]: Verzeichnis „/home/ed/git/tcpflow/build-amake/src“ wird betreten
depbase=`echo dfxml/src/dfxml_writer.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src/be13_api -I../../src/wifipcap -pthread -I/usr/local/include -I/usr/local/include  -DUTC_OFFSET=+0200   -g -pthread -g -O3 -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Weffc++ -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Wstrict-null-sentinel -Weffc++  -MT dfxml/src/dfxml_writer.o -MD -MP -MF $depbase.Tpo -c -o dfxml/src/dfxml_writer.o ../../src/dfxml/src/dfxml_writer.cpp &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo netviz/plot_view.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../../src -I..  -I../../src/be13_api -I../../src/wifipcap -pthread -I/usr/local/include -I/usr/local/include  -DUTC_OFFSET=+0200   -g -pthread -g -O3 -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Weffc++ -Wall -MD -D_FORTIFY_SOURCE=2 -Wpointer-arith -Wshadow -Wwrite-strings -Wcast-align -Wredundant-decls -Wdisabled-optimization -Wfloat-equal -Wmultichar -Wmissing-noreturn -Woverloaded-virtual -Wsign-promo -funit-at-a-time -Wstrict-null-sentinel -Weffc++  -MT netviz/plot_view.o -MD -MP -MF $depbase.Tpo -c -o netviz/plot_view.o ../../src/netviz/plot_view.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ../../src/be13_api/feature_recorder.h:60:0,
                 from ../../src/be13_api/bulk_extractor_i.h:91,
                 from ../../src/tcpflow.h:255,
                 from ../../src/netviz/plot_view.cpp:12:
../../src/dfxml/src/hash_t.h:192:16: error: field ‘mdctx’ has incomplete type ‘EVP_MD_CTX {aka evp_md_ctx_st}’
     EVP_MD_CTX mdctx;      /* the context for computing the value */
                ^~~~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /usr/include/openssl/hmac.h:15,
                 from ../../src/dfxml/src/hash_t.h:57,
                 from ../../src/be13_api/feature_recorder.h:60,
                 from ../../src/be13_api/bulk_extractor_i.h:91,
                 from ../../src/tcpflow.h:255,
                 from ../../src/netviz/plot_view.cpp:12:
/usr/include/openssl/ossl_typ.h:92:16: note: forward declaration of ‘EVP_MD_CTX {aka struct evp_md_ctx_st}’
 typedef struct evp_md_ctx_st EVP_MD_CTX;
                ^~~~~~~~~~~~~
In file included from ../../src/be13_api/feature_recorder.h:60:0,
                 from ../../src/be13_api/bulk_extractor_i.h:91,
                 from ../../src/tcpflow.h:255,
                 from ../../src/netviz/plot_view.cpp:12:
../../src/dfxml/src/hash_t.h: In member function ‘void hash_generator__<md, SIZE>::release()’:
../../src/dfxml/src/hash_t.h:211:31: error: there are no arguments to ‘EVP_MD_CTX_cleanup’ that depend on a template parameter, so a declaration of ‘EVP_MD_CTX_cleanup’ must be available [-fpermissive]
      EVP_MD_CTX_cleanup(&mdctx);
                               ^
../../src/dfxml/src/hash_t.h:211:31: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
Makefile:756: die Regel für Ziel „netviz/plot_view.o“ scheiterte

**Comment by simsong** [comment]
Apparently Debian "sid" is ["The Unstable distribution." ](https://www.debian.org/releases/sid/).

I am closing this issue. Please open it again if/when tcpflow does not compile on a stable Debian distribution.

**Comment by Code7R** [comment]
Hello @simsong , you are apparently unaware of Debian's release process. "Unstable" does not mean "broken". For potentially broken stuff, Debian has the "experimental" branch.

Unstable is the development basis for most software. Even the current Frozen/Testing branch (to be released soon) is a recent spin-off from that.

Apart from that, here, I make the compiler message readable for you:

../../src/dfxml/src/hash_t.h:211:31: error: there are no arguments to ‘EVP_MD_CTX_cleanup’ that depend on a template parameter, so a declaration of ‘EVP_MD_CTX_cleanup’ must be available [-fpermissive]
EVP_MD_CTX_cleanup(&mdctx);
and https://www.openssl.org/news/changelog.html will explain why those functions were removed.

The problem is obviously tcpflow's flaw because it expects legacy OpenSSL but does not detect incompatible versions. And yes, I call 1.0.x legacy because 1.1.x has been out there for quite a while now and will also be the default version in upcoming Debian, see https://packages.debian.org/search?keywords=libssl-dev .

**Comment by simsong** [comment]
I am aware of this, but I do not have the time to track experimental operating systems. Is this a Sid problem or an OpenSSL problem? If you want to submit a pull request with the fix, that's fine. Otherwise I will wait until I can test this in an OS I can easily download and install.

Sorry!! I am not being funded to maintain this program...
