### ISSUE TITLE
'expression' is not explained in docs

### ISSUE THREAD

**Issue by funkyfuture** [simsong/tcpflow#150]
in the man-page i can read `expression` in the cli spec, yet there are no further mentions of it. there are two example expressions, but not syntax or token reference.

**Comment by hansfn** [comment]
Just repeating from my PR #183: 

> Expression is explained in the man page for tcpflow 1.5.0-alpha1, but it was incomplete and pointing to wrong man page for syntax. This patch basically uses the text from tcpdump.
