### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by simsong** [simsong/tcpflow#158]
Need to add support for github's continuous integration.

**Comment by simsong** [comment]
Look like https://github.com/marketplace/circleci is the one to use.

**Comment by sebix** [comment]
I know how to write travis files, but could also look into circleci. Any reason to prefer the latter?

**Comment by simsong** [comment]
Circleci looked good because it is free and packaged into GitHub. Is there anything like that for travis?

**Comment by sebix** [comment]
Both are very well integrated with github. Or do you also want to provide builds for download from CI directly?

**Comment by simsong** [comment]
I have no knowledge of either. I’m looking for someone to pick up the batton.

CI had a free service when I looked it over; does the other one?

**Comment by sebix** [comment]
Am 2018-02-19 um 22:25 schrieb Simson L. Garfinkel:
> I have no knowledge of either. I’m looking for someone to pick up the
> batton.

I can do that :)
> CI had a free service when I looked it over; does the other one?

Both are free for OSS projects

**Comment by simsong** [comment]
Great! A simple integration that tests our builds and automatically makes the distribution would be wonderful. Let me know what you need.
