### ISSUE TITLE
tcpflow does not properly reassemble TCP streams containing retransmissions and out of order packets

### ISSUE THREAD

**Issue by mwallace582** [simsong/tcpflow#162]
I am seeing an issue with tcpflow version 1.4.5 where TCP packets are not reassembled properly when they appear out of sequence in the recording.

The sequence basically looks like this when viewed in wireshark:

1. Seqno 1
2. Seqno 3 [TCP previous segment not captured]
3. Seqno 2 [TCP retransmission]
4. Seqno 4

When processed with `tcpflow -cCs -r <pcap_file>`, the bytes within the packets are printed out like so:
Seqno 1
Seqno 3
Seqno 2
Seqno 4

My assumption is that tcpflow should be reordering these based on the TCP sequence numbers. Is this one of the goals of the utility? I would be happy to dig through the code and try to fix the bug if the tool had previously functioned this way, but since has broken.

I've got a small pcap demonstrating this which I can share via email if necessary.

**Comment by simsong** [comment]
Thanks. It looks like you have found a bug. It would be great if you could debug this. Even better, if you could make the packets publicly available so we could add them to the tcpflow test suite.

**Comment by mwallace582** [comment]
I'll get started trying to resolve it. Do you happen to know if this is a regression or just something which has never been noticed? I just tested the same capture with tcpflow 0.21 and saw the same bug, so my guess is that it was never noticed.

I will provide the packets publicly, but I will need to do some editing on them beforehand, as there is some mildly sensitive information contained within.

**Comment by simsong** [comment]
Okay, please remove the sensitive info, but you will need to fix the checksums, too. It may be easier to take a new capture and just reorder two packets in the stream, if that is all that is required.

**Comment by mwallace582** [comment]
I plan to try [WireEdit](https://wireedit.com/), but I won't have access to a Windows computer until tonight. It is supposed to be able to fix up all the fields which depend on the contents of the payload.

**Comment by simsong** [comment]
Great! We need more tests cases and a unit test framework.

**Comment by mwallace582** [comment]
Have you considered using google's gtest framework for unit tests? I use it frequently and it's very easy to integrate and use. I'm sure there are a million frameworks out there though.

**Comment by simsong** [comment]
I am not familiar with C++ frameworks; I am looking for recommendations.


----
Sent from my phone.

On Jun 9, 2017, at 11:31 AM, mwallace582 <notifications@github.com> wrote:

Have you considered using google's gtest framework for unit tests? I use it frequently and it's very easy to integrate and use. I'm sure there are a million frameworks out there though.

**Comment by mwallace582** [comment]
Gtest is great for either C or C++. But it's also the only one that I've used so there might be better ones out there.

Also, I figured out the cause of the issue that I reported initially. Looks like the reordering is done as the data is written to the output file, and printing data to the console is done earlier as the packets are processed.

A solution that comes to mind is to create an in-memory list to buffer out of order packets until the earlier ones have arrived. This would have a large memory footprint if there are a lot of out of order packets or if the packets themselves are large.

What do you think?

**Comment by simsong** [comment]
I think that we should document that console output is in packet-order, and may not agree with file order.

**Comment by mwallace582** [comment]
The reason this issue came up is that I'm using the console output of tcpflow to feed another program. I need the data stream to be in the proper order for this other program to function properly.

If this behavior is intended, I can look into using another utility to perform this function. Otherwise, I can make the change that I mentioned and maybe make it optional via a new command line flag.

**Comment by mwallace582** [comment]
I'd like to either resolve this or move on to something else. Would you be in support of me making the change I mentioned above?

**Comment by simsong** [comment]
I thought this was resolved.

I don't see a problem in principle with having a small packet reordering buffer for console output. But you won't want to do it packet by packet. What happens ifnocjets overlap? What happens if there is a long delay between the packets? Really, I think that you want a fundamentally different approach for generating console output that is based on the reassembled streams, not the packets. Do you want to write that?

**Comment by mwallace582** [comment]
For the time being I am going to work around the issue by pre-processing my PCAP files instead of relying on tcpflow's console output. I'm going to close this issue.
