### ISSUE TITLE
inet_ntop confusion

### ISSUE THREAD

**Issue by sebix** [simsong/tcpflow#174]
Hi,

I tried to build the alpha2 version from http://downloads.digitalcorpora.org/downloads/tcpflow/ and I'm failing with the inet_ntop.h file. The ./configure script checks if it is delared and defines HAVE_INET_NTOP accordingly.
But: the file `inet_ntop.h/c` is not included in the tarball, but here on github it is: https://github.com/simsong/tcpflow/blob/master/src/inet_ntop.h
The inet_ntop.h file is needed in tcpip.h and tcpflow.h

Btw: here on github the alpha2 tag is missing

**Comment by simsong** [comment]
Okay. Thanks for reporting this. Can try to build from sources on your platform using a “git clone” ?

**Comment by sebix** [comment]
> Can try to build from sources on your platform using a “git clone”

(And all submodules loaded), yes

**Comment by simsong** [comment]
Great. Can you submit a patch request that add inet_ntop.h to the list of files that are included in the installer?

**Comment by sebix** [comment]
> Can you submit a patch request that add inet_ntop.h to the list of files that are included in the installer?

No, because I don't know how you generate the tarballs and what I need to do that this file get's included the next time :/

**Comment by simsong** [comment]
We use autoconf. I just added this to src/Makefile.am:

        inet_ntop.c \
        inet_ntop.h \
