### ISSUE TITLE
A new 1.5.0 (beta) release

### ISSUE THREAD

**Issue by hansfn** [simsong/tcpflow#184]
It seems there has been many changes since 1.5.0 alpha1 which is the only release available here on GitHub. It's also confusing that there is alpha2 on the download page and a mention of alpha3 in a commit message. All of these alphas are more than a year old.

What is needed to get a new (beta) release of 1.5.0? Some blocker issues or (build) tests that needs to be done?

Please let us know how we can help.

**Comment by simsong** [comment]
I needed a push. I’ve been letting people do testing. But you are right. This weekend!

**Comment by simsong** [comment]
tcpflow release 1.5.0 can now be downloaded from http://downloads.digitalcorpora.org/downloads/tcpflow/
