### ISSUE TITLE
tcpflow 1.5.0 missing configure script

### ISSUE THREAD

**Issue by fxcoudert** [simsong/tcpflow#192]
The released source tarball of tcpflow 1.5.0 is missing the configure script. This is preventing us from updating the version in Homebrew: https://github.com/Homebrew/homebrew-core/pull/32412

(I tried to `bash ./bootstrap.sh` to regenerate the `configure` script, but it also fails because `not a git repository`)

**Comment by simsong** [comment]
How odd. I will fix. Thanks.


----
Sent from my phone.

On Sep 25, 2018, at 7:09 AM, FX Coudert <notifications@github.com> wrote:

The released source tarball of tcpflow 1.5.0 is missing the configure script. This is preventing us from updating the version in Homebrew: Homebrew/homebrew-core#32412

(I tried to bash ./bootstrap.sh to regenerate the configure script, but it also fails because not a git repository)

**Comment by simsong** [comment]
I believe that you are mistaken. There is clearly a configure script present:


[Dance ~/gits/tcpflow 08:17:20](master)↑ $ tar tfvz tcpflow-1.5.0.tar.gz |grep configure
-rw-r--r--  0 simsong staff   19608 Aug 19 11:13 tcpflow-1.5.0/configure.ac
-rwxr-xr-x  0 simsong staff  322980 Aug 19 11:15 tcpflow-1.5.0/configure
-rw-r--r--  0 simsong staff    1306 Aug 20  2017 tcpflow-1.5.0/src/be13_api/be13_configure.m4
-rw-r--r--  0 simsong staff    2666 Aug 20  2017 tcpflow-1.5.0/src/dfxml/src/dfxml_configure.m4
[Dance ~/gits/tcpflow 08:17:29](master)↑ $

**Comment by fxcoudert** [comment]
```
bli /tmp $ wget -q https://github.com/simsong/tcpflow/archive/tcpflow-1.5.0.tar.gz
bli /tmp $ tar xfz tcpflow-1.5.0.tar.gz 
bli /tmp $ ls tcpflow-tcpflow-1.5.0/config*
tcpflow-tcpflow-1.5.0/configure.ac
```

**Comment by simsong** [comment]
https://github.com/simsong/tcpflow/archive/tcpflow-1.5.0.tar.gz is not the distribution point of the archive. That is a release made automatically by github creating a .tar.gz archive of the 1.5 tagged release. That doesn't work, obviously, for a whole bunch of reasons—mostly that tcpflow uses submodules.  

If you want the .tar.gz file, you should get it from the published release point:

http://downloads.digitalcorpora.org/downloads/tcpflow/tcpflow-1.5.0.tar.gz

**Comment by fxcoudert** [comment]
The problem we're having with the distribution point is that it is removing the older versions of the software (or at least moving them), which breaks our distribution for users when a new version is released. Please consider hosting versions at a stable URL.

**Comment by simsong** [comment]
We do have it hosted at a stable URL:

http://downloads.digitalcorpora.org/downloads/tcpflow/ <http://downloads.digitalcorpora.org/downloads/tcpflow/>

Are you saying you want a name for a '.tar.gz' file that does not include the version number?

**Comment by fxcoudert** [comment]
Sorry if I was unclear. I mean we would prefer that `
http://downloads.digitalcorpora.org/downloads/tcpflow/tcpflow-1.5.0.tar.gz` continue to exist after the next version is released. That way, build from source is not broken for users in the time it takes for us to update the formula to the next version.

**Comment by simsong** [comment]
Sure. Typically we leave the .tar.gz files there for 3-5 years. We just cleaned house recently and moved the old releases into the attic.

**Comment by fxcoudert** [comment]
Great, thanks
