### ISSUE TITLE
broken build facilities

### ISSUE THREAD

**Issue by cherusk** [simsong/tcpflow#199]
Could you kindly revise that your build mechanisms are working?

Tried on recent Ubuntu/Fedora, none worked, all failing with obscure glitches:

E.g.:
[...]
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details

---
configure:6188: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details

**Comment by cherusk** [comment]
That's unthinkable!

**Comment by simsong** [comment]
I need a better bug report. Which version of os, compiler, etc?

**Comment by cherusk** [comment]
Fedora28, Ubuntu xenial and latest: If you get the lastest container image, you should have the tooling ecosystem to reproduce.

**Comment by simsong** [comment]
Did you run the script that prepares the VM first?

**Comment by cherusk** [comment]
Absolutely, followed your procedure(s). Have you ran it?

**Comment by simsong** [comment]
Not yet, but perhaps this weekend!

**Comment by simsong** [comment]
Nothing was broken about the build; you didn't have C++ installed. I've updated the install script for FEDORA_29.
