### ISSUE TITLE
Unable to see UDP traffic

### ISSUE THREAD

**Issue by rb07** [simsong/tcpflow#2]
Hi,

Using tcpflow version 1.2.6, with libpcap 1.2.1, in a NAS which is running Linux 2.6.12, I'm unable to see any UDP traffic.

I'm guessing is a problem in my environment, but I just tested with tcpdump and that works.

Any ideas?

**Comment by davidnewhall** [comment]
For anyone else winding up here after trying to dump UDP packets with tcpflow, two things to note:
1. There is an older version of tcpflow written by [Jeremy Elson](mailto:jelson@circlemud.org) that has a [man page](https://www.circlemud.org/jelson/software/tcpflow/tcpflow.1.html) on the Internet that seems to indicate tcpflow supports UDP. This man page looks a lot like the one included with the version of tcpflow in this repo.
1. Neither version of `tcpflow` supports UDP processing.

Good luck!

**Comment by simsong** [comment]
> For anyone else winding up here after trying to dump UDP packets with tcpflow, two things to note:
> 
> 1. There is an [older version of tcpflow](https://www.circlemud.org/jelson/software/tcpflow/#HISTORY) written by [Jeremy Elson](mailto:jelson@circlemud.org) that has a [man page](https://www.circlemud.org/jelson/software/tcpflow/tcpflow.1.html) on the Internet that seems to indicate tcpflow supports UDP. This man page looks a lot like the one included with the version of tcpflow in this repo.
> 2. Neither version of `tcpflow` supports UDP processing.
> 
> Good luck!

1. I took over tcpflow from [Jeremy Elson] many years ago.

2. What would it mean for a program that processes TCP packets to support "UDP processing." What does that even mean?

**Comment by davidnewhall** [comment]
1. Thank you for the explanation.
2. I'm not a network engineer, but I understand packets well enough. My very very simple answer is another question, sorry: "can't it just work with udp like tcpdump does?" I've been looking for a way visualize statsd packets with ip headers, and tcpdump is the only tool I have, but it's output is awful; lots of nonprintable characters make lots of periods and random letters at the beginning of the packet. The command I ran that I was hopeful would work is: `tcpflow -c udp port 8125`

Thanks so much for the reply!

**Comment by simsong** [comment]
The answer to your question ""can't it just work with udp like tcpdump does?" "no, it can't, because the udp packets aren't structured as a continuous stream of human-readable text."
