### ISSUE TITLE
tcpflow: seg fault on interrupt

### ISSUE THREAD

**Issue by Lechnio** [simsong/tcpflow#224]
I realized that a segmentation fault occurs when listening was interrupted with <i>Ctrl^c</i> and no interface was selected with `-i <interface-name>` option (in this case interface is used for us). For workaround just specify the interface name and all is correct. \
\
That occurred when user did not specify the name of interface to use. In such a case it was allocated inside the function `process_infile` which should get `const char** device` and not `const char* device`. Value of the pointer was lost on function exit. Also there was memory allocation with `strdup` with no free after so I changed it to be `std::string` in order to memory could be released in its destructor automatically.

Memory alloc without free in [line](https://github.com/simsong/tcpflow/blob/7fd918d9b10f49bbc45786b71e043739eb0bb49b/src/tcpflow.cpp#L476)
```
        device=strdup(alldevs[0].name);
```
Main problem was in [here](https://github.com/simsong/tcpflow/blob/7fd918d9b10f49bbc45786b71e043739eb0bb49b/src/tcpflow.cpp#L896)
```
        /* live capture */
	demux.start_new_connections = true;
        int err = process_infile(demux,expression,device,"");
        if (err < 0) {
            exit_val = 1;
        }
        input_fname = device;    // <-- device here is not a value allocated in the 'process_infile' func
```

This is applicable to all version, but the one I use is 1.5.2.
I will pull request patch for it in the minute.

**Comment by simsong** [comment]
Yea! Thanks!
