### ISSUE TITLE
configure script falls in infinite loop of "=yes" output on Centos8 and Centos7

### ISSUE THREAD

**Issue by marko-kukovec** [simsong/tcpflow#228]
I'm trying to build tcpflow on Centos7 and Centos8. I have all prerequisites installed on both systems. On both systems when configure script gets to the point

```
checking whether gcc understands -Wmultichar... yes
checking whether gcc understands -Wc++-compat... yes
checking whether gcc understands -Wmissing-noreturn... yes
checking whether gcc understands -Wall... yes
checking whether gcc understands -Wstrict-prototypes... yes
= yes
= yes
= yes
= yes
= yes
```

it falls in the nonrecoverable infinite loop of `=yes` output

Whole output log until build was manually interrupted with Ctrl+C https://file.io/d0v4j0LWSUy0

**Comment by simsong** [comment]
I discovered this as well. There is a problem in the included makefile. I think that you are best off going with the release, rather than the master branch.

**Comment by awaugh-SI** [comment]
For what its worth, this also happens on AWS Linux.

**Comment by simsong** [comment]
Agreed. I suggest you use the released version. As I indicated, I'm doing a complete rewrite of be13_api, to be followed by a complete rewrite of tcpflow.
