### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by SMillerDev** [simsong/tcpflow#233]
Could you make a release tag? The build will currently identify as 1.6.x, but without a tag it's kind of a moving target to compile for package managers.

**Comment by simsong** [comment]
Sure!

**Comment by simsong** [comment]
@SMillerDev  - Can you check out https://github.com/simsong/tcpflow/tree/master-hotfix-1.6.1 and let me know if it works for you? If so, we'll call it v1.6.1 and we'll post a .tar.gz as well.

**Comment by simsong** [comment]
Done. Thanks for the suggestion.
https://github.com/simsong/tcpflow/releases/tag/tcpflow-1.6.1

**Comment by SMillerDev** [comment]
Thanks @simsong !

**Comment by SMillerDev** [comment]
One more question, will that one be posted to https://downloads.digitalcorpora.org/downloads/tcpflow/ too?

**Comment by simsong** [comment]
> One more question, will that one be posted to https://downloads.digitalcorpora.org/downloads/tcpflow/ too?

Thanks for the suggestion. I just posted it there. (It's a _lot_ easier to put things there now thanks to hosting it on S3.)

BTW, we're always looking for help!
