### ISSUE TITLE
Feature Request: need to Add Stream number

### ISSUE THREAD

**Issue by SoOM3a** [simsong/tcpflow#246]
Hi, 
If there is any possiablity to add stream number for the communication, or add each stream in seprated file. 
As an example 
WebServer <-HttpRequest-- Client
WebServer --Httpresponse-> Client 
So if there is option to store this communication as 1 file per stream or in 2 separated file in same directory(each stream). 
if there is no option can it be a feature request? 
I saw some similar case https://github.com/simsong/tcpflow/issues/8

**Comment by simsong** [comment]
Can you describe specifically what you want. You already have the ability to store files in sub directories by specifying a custom file pattern.

**Comment by SoOM3a** [comment]
I'm trying to extract TCP Stream flow based on TCP stream number in a pcap using TCPflow but the tool dump all the packets without numbering the packets with right TCP stream number.

`.\tcpflow64.exe -o out -a -r example.pcap -T %N_%A-%a_%B-%b.txt -S enable_report=YES`

No info about stream number in tcp flow page nor in the tool --help. 

Request: 
if I have 3 TCP Http Streams, How I can extract each tcp stream separately in separated directory 
1- Stream1 (between ServerA <-> ClientB )
2- Stream2 (between ServerA <-> ClientC)
3- Stream3 (between ServerD <-> ClientT)

**Comment by simsong** [comment]
You'll have to fill me in. I don't know what you mean by "TCP stream number."

**Comment by simsong** [comment]
Did you try this:

```
.\tcpflow64.exe -o out -a -r example.pcap -T %C/%N_%A-%a_%B-%b.txt -S enable_report=YES
```

**Comment by SoOM3a** [comment]
So sorry for late response, normally when open a website 'Ex; facebook' pcap in Wireshark will be show 
1. Client request login page . Client -> Server
2. Server respond with html/css using http response. Server -> client
3. Client request HomePage'. Client -> Server 
4. Server respond in same stream /in same socket . Server -> client 

It will show like this wireshark with packet stream number as the following 


[https://ibb.co/0VQwt5d](WireShark) View for the pcap in wireshark
[https://ibb.co/PN8rWrn](output) missing stream/tcpdata numbering

but the output for the tool missing order, I can not decide which tcp data send first and where the response for this. specially if the pcap contains a lot of tcp sessions for other http connections 

Regards, 
A.Esmail

**Comment by simsong** [comment]
Thanks for posting that. You are correct. WireShark is showing you the two sides of the TCP stream interleaved, and tcpflow is not doing that. There is a single TCP connection between source 10.104.223.178:53473 and 10.104.223.182:80.  It has traffic going in one direction (the requests), then traffic going in the other direction (the response), then back in the first direction (another request), and then in the second direction (the second response).

tcpflow does not have this behavior.

There are only two streams. tcpflow does not show you how streams interleave.

Sorry!
