### ISSUE TITLE
Data corruption due to packets with padding (1.6.1)

### ISSUE THREAD

**Issue by Dimon160** [simsong/tcpflow#261]
Short TCP4 packets with Ethernet padding and no stream data (window manipulation, etc.) may corrupt output files, because of incorrect length using.
Also, tcpflow creates 2-3 unwanted files, contain only two zero bytes.
In my case, I get regular one corrupted byte, every ~350Mbytes.

Attached patch fix both problems.

[patch-tcpdemux-cpp.txt](https://github.com/user-attachments/files/15757437/patch-tcpdemux-cpp.txt)

**Comment by simsong** [comment]
That is great! Can you please submit this as a pull request? Even better, do you have a PCAP file that demonstrates this problem? If so, please submit that too, so that we can add a unit test for it.

**Comment by simsong** [comment]
I can make a pull request. Can you make a smaller PCAP file? Ideally 10-100kb?

**Comment by Dimon160** [comment]
It seems to do it.
Following archive, contain very small PCAP file, that demonstrates two stream decoding errors, and one unwanted file.
Maybe it's similar to #253 and #258 issues.

[pcap.zip](https://github.com/user-attachments/files/15786284/pcap.zip)
