### ISSUE TITLE
bootstrap.sh fails with no error but 

### ISSUE THREAD

**Issue by Saylrman64** [simsong/tcpflow#52]
Ran commands exactly as indicated:
Be sure you have the necessary precursors:
# yum -y install git gcc-c++ automake autoconf boost-devel cairo-devel libpcap-devel zlib-devel

Download the sources with git, run bootstrap.sh, configure and make:
git clone --recursive https://github.com/simsong/tcpflow.git
cd tcpflow
sh bootstrap.sh

All Yum installs went fine but when I ran #sh bootstrap.sh it ends abruptly with the following output:
src/Makefile.am:50: compiling `http-parser/http_parser.c' in subdir requires`AM_PROG_CC_C_O' in `configure.ac'

Server is CentOS 6

**Comment by simsong** [comment]
Closing this because CentOS 6 is no longer in use.
