### ISSUE TITLE
Tcpflow fails on some ARM an SPARC chips

### ISSUE THREAD

**Issue by dkogan** [simsong/tcpflow#67]
Hi.

I'm seeing problems with tcpflow built on ARM and SPARC:

 https://buildd.debian.org/status/package.php?p=tcpflow

The build log shows that test1.sh failed. I traced the issue to unaligned memory
loads. Specifically,
1. tcpdemux::process_tcp() is called with some arbitrary ip_data bytes.
2. process_tcp() does this:
   
   struct be13::tcphdr *tcp_header = (struct be13::tcphdr *) ip_data;
   
   Here we reinterpret the ip_data bytes as a tcphdr structure. This structure
   can have ANY alignment since it came from an array of bytes
3. When we reference this structure (for instance in tcp_header->th_seq), C
   assumes ALIGNED data, as it always does.

The specific behavior of unaligned memory access varies by architecture. On x86
things work, although there is a performance hit. On ARM the behavior appears to
be undefined. Some chips do what you would expect, while some others assume the
address is aligned, and thus end up accessing the wrong memory. On SPARC, you
get a bus error and the program crashes.

Some ways to resolve this:
- we can make sure the input data is aligned
- we can mark be13::tcphdr as **attribute**((packed)). This will cause all
  accesses to this structure to happen a byte at a time, which would fix the
  issue, but a performance hit would result any time anything is done with this
  structure

**Comment by simsong** [comment]
@dkogan  - is this still an issue?

**Comment by dkogan** [comment]
Hi. Currently the latest tcpflow release builds on all the Debian architectures. This is solved. I'm closing it. Thanks.
