### ISSUE TITLE
tcpflow prints "write error to stdout" after every packet

### ISSUE THREAD

**Issue by dkogan** [simsong/tcpflow#74]
Hi. This is forwarded from debian bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736417

This applies when tcpflow is invoked with -c.

From: Frank Gevaerts frank@gevaerts.be
To: Debian Bug Tracking System submit@bugs.debian.org
Subject: tcpflow prints "write error to stdout" after every packet
Date: Thu, 23 Jan 2014 14:20:18 +0100
Package: tcpflow
Version: 1.4.4+repack1-2
Severity: normal

tcpflow prints "write error to stdout" after every packet. This is printed when the expected length and the actually written length are different, in tcpip.c line 272.
The root cause is that the written length is not calculated correctly.

On line 265, written is incremented by the output of fputc(), which seems to be assumed to be 1 in case a character is successfully written. However, fputc() is defined as returning the character actually written. One solution would be:

```
--- tcpflow-1.4.4+repack1.orig/src/tcpip.cpp
+++ tcpflow-1.4.4+repack1/src/tcpip.cpp
@@ -262,7 +262,7 @@ void tcpip::print_packet(const u_char *d
     else if(demux.opt.output_strip_nonprint){
        for(const u_char *cc = data;cc<data+length;cc++){
            if(isprint(*cc) || (*cc=='\n') || (*cc=='\r')){
-               written += fputc(*cc,stdout);
+               written += (fputc(*cc,stdout)!=EOF);
            }
        }
     }
```

Frank

**Comment by md5** [comment]
> That was fixed quite some time ago.

I'm running into this same issue in the Alpine `tcpflow` package. Looks like they're still building off the 1.4.4 source package, so they don't have this fix (cf. http://git.alpinelinux.org/cgit/aports/tree/main/tcpflow/APKBUILD?id=3b914bb4d41007268c724a55b3a072fed2c305e0#n14)

Any chance you have any plans to cut a new release? It looks like there have been a bunch of changes since 1.4.4: https://github.com/simsong/tcpflow/compare/tcpflow-1.4.4...master

**Comment by simsong** [comment]
Sure. I'll give it a try.

**Comment by simsong** [comment]
Release 1.4.5 is issued.

**Comment by md5** [comment]
@simsong I'm not seeing a new build at http://www.digitalcorpora.org/downloads/tcpflow/ or a new tag or release at https://github.com/simsong/tcpflow/releases

Where can I find 1.4.5?

**Comment by simsong** [comment]
I pushed the tag.

**Comment by md5** [comment]
Thanks @simsong!

Was there anything special about the source tarballs at Digital Corpora, or would it be a drop-in replacement to use the tarballs generated by GitHub? (e.g. https://github.com/simsong/tcpflow/archive/tcpflow-1.4.5.tar.gz)

**Comment by simsong** [comment]
Github tarballs don't have "configure" scripts, because they don't run autoconf.

**Comment by md5** [comment]
Makes sense. I didn't see a target in the `Makefile.am` to upload the `*.tar.gz` to Digital Corpora, just the `*.zip` release. Any chance you'd be willing to publish a new source tarball?

Thanks again for your attention to this.

**Comment by simsong** [comment]
At some point, but not today.

**Comment by dkogan** [comment]
While you're at it, can you change the main heading of README.md to reflect the current version? It still says "tcpflow 1.3"

**Comment by md5** [comment]
@dkogan See https://github.com/simsong/tcpflow/pull/105
