### ISSUE TITLE
Incorrect timestamps in index files

### ISSUE THREAD

**Issue by dsmithbbn** [simsong/tcpflow#93]
When writing index files, the tv_usec component of the timestamp is not formatted correctly as a string because the value is not being 0-padded.

Ex. A packet with a timestamp like

    Jan 23, 2015 09:58:16.085085000 EST

is incorrectly rendered as

    1422025096.85085

in the index file.

**Comment by simsong** [comment]
Good catch. Please feel free to fix the bug and issue a pull request.
