### ISSUE TITLE
Download Location Not Working

### ISSUE THREAD

**Issue by mahiuchun** [simsong/tcpflow#97]
http://www.digitalcorpora.org/downloads/tcpflow/ is not working.

This also affects Homebrew:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tcpflow.rb

**Comment by simsong** [comment]
Okay. DOwnload from github.

**Comment by mhricher** [comment]
Thanks for reporting the problem with digitalcorpora.org<http://digitalcorpora.org>.

The folks who are hosting the site have resolved the problem.

Mark

MARK H RICHER, MS CS
Faculty Research Associate
Computer Science Department
Naval Postgraduate School - National Capital Region (NCR)
703-275-8533 (o) 571.303.9498 (m) mhricher@nps.edu<mailto:mhricher@nps.edu>


On May 1, 2015, at 1:21 AM, Hill Ma <notifications@github.com<mailto:notifications@github.com>> wrote:


http://www.digitalcorpora.org/downloads/tcpflow/ is not working.

This also affects Homebrew:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tcpflow.rb
