### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [simsong/tcpflow#99]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [node](https://github.com/simsong/tcpflow/blob/cdfa9fb03978d62c807927db171dd71f5f28e21e/src/iptree.h#L88)
- [tcpdemux](https://github.com/simsong/tcpflow/blob/5eb5bd1dc8a918f6dee57c3b68558d51d8acf9b6/src/tcpdemux.h#L82)
- [tcpip](https://github.com/simsong/tcpflow/blob/5eb5bd1dc8a918f6dee57c3b68558d51d8acf9b6/src/tcpip.cpp#L96)

**Comment by simsong** [comment]
Why are they not needed?

**Comment by elfring** [comment]
The standard specifications contain descriptions that [the C++ delete operator will tolerate passed null pointers already](http://en.cppreference.com/w/cpp/language/delete "Description for delete expressions"), don't they?

**Comment by simsong** [comment]
Okay. I was not aware of this. Thanks, I will fix.

**Comment by simsong** [comment]
Fixed in 57d97ac.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/simsong/tcpflow/commit/57d97ac3498c9f587af974848ad0297bd1585675 "removed null checks before delete").
